# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tale',
            old_name='author',
            new_name='author_id',
        ),
    ]
