# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0002_auto_20170719_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tale',
            name='header_img',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
