# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 04:10
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tales', '0004_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
